services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Mindbird\Contao\Person\:
    resource: '../src/'

  Mindbird\Contao\Person\Migration\MoveModulesToContentElementsMigration:
    tags:
      - { name: contao.migration, priority: 0 }